create database customer_behavior;
use customer_behavior;
Select * from customer limit 20;

#1 Total Revenue generated by each gender
Select gender, sum(purchase_amount)
As revenue_generated from customer
Group By gender;

#2 which customer spent more than the average purchase amount using discount 
Select customer_id, purchase_amount
from customer 
Where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

#3 Top 5 product with the highest average review rating
Select item_purchased, Round(avg(review_rating),2) 
As avg_review_rating from customer
Group By item_purchased
Order By avg(review_rating)
Desc Limit 5;

#4 Compare the avg purchase amount between standard and express shipping
Select Round(avg(purchase_amount),2), shipping_type
from customer
Where shipping_type in ('Standard', 'Express')
Group By shipping_type;

#5 compare avg spend and total revenue between subscribers and non_subscribers
Select subscription_status, count(customer_id)
as total_customers, Round(avg(purchase_amount),2) as avg_spend, 
Round(sum(purchase_amount),2) as revenue
from customer
Group By subscription_Status;

#6 Top 5 product having the highest percentage of purchase with discount applied
Select item_purchased, Round(sum(Case When discount_applied = 'Yes' Then 1 Else 0 End)/Count(*)*100,2) as discount_rate
from customer
Group By item_purchased
Order By discount_rate 
Desc Limit 5;

#7 segment customer into New, Returning and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
Select customer_id, previous_purchases,
Case 
	When previous_purchases = 1 Then 'New'
    When previous_purchases Between 2 and 10 Then 'Returning'
    Else 'Loyal'
    End as customer_segment
from customer
)

Select customer_segment, count(*) as number_of_customers
from customer_type
Group By customer_segment;

#8 Top 3 purchased product within each category
with item_count as (
Select category,
item_purchased,
Count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

Select item_rank, category, item_purchased, total_orders
from item_count
where item_rank <= 3;

#9 Are customers who are repeat buyers(more than 5 previous purchases) also likely to subcribe
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

#10 What is the revenue contribution of each age group
Select age_group, sum(purchase_amount) as revenue
from customer
group by age_group
order by revenue Desc;




